changelog:
  exclude:
    labels:
      - 👨‍🦯 Ignore for release
      - 📚 Documentation
  categories:
    - title: 💥 New feature
      labels:
        - 💥 New feature
    - title: ☀️ Enhancement
      labels:
        - ☀️ Enhancement
    - title: 🐞 Bug fix
      labels:
        - 🐞 Bug fix
    - title: Other Changes
      labels:
        - "*"